In [6]:
import numpy as np
arr = np.array([[2,3,4],[3,5,1],[3,3,1]])
np.linalg.det(arr)

np.float64(-20.000000000000007)

In [22]:
eseigneVec,eigvalu = np.linalg.eig(arr)
eigvalu

array([[-0.59248915, -0.78827532,  0.67627896],
       [-0.63953263,  0.26506951, -0.64248608],
       [-0.48985164,  0.55530187,  0.36035871]])

In [23]:
eseigneVec

array([ 8.54527505, -1.82660211,  1.28132705])

In [31]:
u,s,Vt = np.linalg.svd(arr)
u

array([[-0.56559294,  0.82223502, -0.06351538],
       [-0.66335851, -0.49935704, -0.55731323],
       [-0.4899593 , -0.27307896,  0.82786941]])

In [32]:
s

array([8.64757825, 2.73986188, 0.84412512])

In [34]:
Vt

array([[-0.53091619, -0.74974161, -0.39498799],
       [-0.24557368, -0.30998534,  0.91847844],
       [ 0.811062  , -0.58463373,  0.01954057]])

In [3]:
## Calculus derivative
import sympy as sp
x,y = sp.symbols('x y')
f = x**2 + y**2
grad_x= sp.diff(f, x)
grad_y = sp.diff(f, y)
print(grad_x,grad_y)

2*x 2*y


In [5]:
# INTEGRAL
x = sp.Symbol('x')
f = x**2
definiteIntegral = sp.integrate(f,(x,1,4))
indefinite_integral =  sp.integrate(f,x)
definiteIntegral, indefinite_integral

(21, x**3/3)